name: Build, Test, and Push to AWS ECR

on:
  push:
    branches:
      - master  # Runs only when pushing to master

jobs:
  build-and-push:
    name: Build, Test, and Push Docker Image to AWS ECR
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to AWS ECR
      - name: Authenticate to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPOSITORY }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ecommerce-backend:latest .

      # Tag the image for AWS ECR
      - name: Tag Docker Image
        run: |
          docker tag ecommerce-backend:latest ${{ secrets.AWS_ECR_REPOSITORY }}:latest

      # Push Image to AWS ECR
      - name: Push Image to AWS ECR
        run: |
          docker push ${{ secrets.AWS_ECR_REPOSITORY }}:latest

      # Verify Image in ECR (optional)
      - name: List Images in AWS ECR
        run: |
          aws ecr list-images --repository-name ${{ secrets.AWS_ECR_REPOSITORY }}

